"""Initial migration

Revision ID: 986e20fbd400
Revises: 
Create Date: 2023-03-18 21:29:48.134714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986e20fbd400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
